- .github/workflows/main.yml
- doc/source/api/montepy.input_parser.input_file.rst
- doc/source/api/montepy.input_parser.rst
- doc/source/faq.rst
- doc/source/index.rst
- doc/source/utilities.rst
- montepy/__init__.py
- montepy/_scripts/change_to_ascii.py
- montepy/constants.py
- montepy/input_parser/input_file.py
- montepy/input_parser/input_reader.py
- montepy/input_parser/input_syntax_reader.py
- montepy/mcnp_problem.py
- pyproject.toml
- scripts/change_to_ascii.py
- tests/constants.py
- tests/inputs/bad_encoding.imcnp
- tests/inputs/unicode.imcnp
- tests/test_integration.py
- tests/test_scripts.py
Adds:
- `MCNP_InputFile` to documentation site.
- Added encoding options when opening a file, and to `input_reader`
- Added script utility to strip out all non-ascii characters.
this works by:
- reading into UTF-8 with replace.
- Replaced replaced characters with nothing or `' '`
- Covert back to ascii. Anything about 128 also gets converted. 
- Added utilities section to guide
- Added FAQ that shows a typical stack trace
Needs still:
Closes #186, #334.
> Overhaul how character encoding is handled. 

- montepy/input_parser/input_syntax_reader.py
- tests/inputs/test.imcnp
- tests/test_integration.py
Vertical mode detection accidentally wasn't considering comments. This fixed this logic.
Fixes #370.
> Fix bug with hidden vertical input mode. 

- pyproject.toml
This is a quick fix for coveralls.
> updated coverage options to make coverall paths work.

- doc/source/changelog.rst
- pyproject.toml
It was noticed that on PyPI Brenna was showing up as the author: https://pypi.org/project/montepy/0.2.7/. While her contributions are important, having her as the point of contact for a project that she is not responsible for is a bit of a big ask. 
After further investigation this comes down to how the data are packaged in the wheel as that's what PyPI reads.
The problematic wheel (0.2.7) has the `METADATA` file that looks like:
``` 
Metadata-Version: 2.1
Name: montepy
Version: 0.2.7
Summary: A library for reading, editing, and writing MCNP input files
Author: Brenna Carbno
Author-email: Micah Gale <micah.gale@inl.gov>, Travis Labossiere-Hickman <Travis.LabossiereHickman@inl.gov>
Maintainer-email: Micah Gale <micah.gale@inl.gov>
License: MIT License
```
It appears that `author` takes …
> Fixed Project metadata to have authorship be clearer on PyPI

- doc/source/conf.py
- doc/source/starting.rst
Add a `:manual63:` command to link to relevant sections of the MCNP6.3 user's manual. Apply it in "Getting Started".
Note that LANL used a nice, predictable subsection naming convention for MCNP6.3, and did not for MCNP6.2.
Motivation: prerequisite to address #413.
- Should I add a note to the developer's guide? If not, then not applicable.
> Command to automatically link to MCNP manual

- .github/workflows/main.yml
- .gitignore
- README.md
- doc/source/_test_for_missing_docs.py
- doc/source/changelog.rst
- doc/source/conf.py
- doc/source/developing.rst
- doc/source/starting.rst
- montepy/cell.py
This is currently a draft playbox right now. 
This won't address #413, but put the machinery in place for it.  This is also related to #414, but won't close it. 
Fixes #412, fixes #416.
> Add references to MCNP user manual and documentation updates

- doc/source/changelog.rst
- doc/source/index.rst
This does:
* Point to OSTI on the index for the MCNP 6.3 manual.
* DOI is included as a separate link as this links directly to the pdf. 
* Moved MCNP 6.3 up to make it reverse chronological order. 
Fixes #424
> Updated index to use OSTI/DOI for MCNP 6.3

- .github/workflows/main.yml
- montepy/mcnp_object.py
Add some additional logic to check if any code in `montepy/` was updated. 
Todo: squash
Fixes #436
> Pass changelog-test when no code is modified

- doc/source/changelog.rst
- doc/source/starting.rst
- montepy/input_parser/input_file.py
- montepy/mcnp_problem.py
- tests/test_input_file.py
- tests/test_integration.py
This introduces a new argument to `MCNP_Problem.write_to_file`, (and `montepy.input_parser.input_file.write_to_file.open`), `overwrite`, which indicates if the existing file should be overwritten. The default behavior is to raise a `FileExistsError` if the file exists, and overwrite is not specified. This error is ignored in `overwrite=True`. No matter what a `IsADirectoryError` is raised if the path is a folder.
Thanks @tjlaboss  for the prototyping.
Fixes #442
> Implemented overwrite guardrails thanks to @tjlaboss.

- .github/workflows/deploy.yml
- .github/workflows/main.yml
- pyproject.toml
An upstream bug with Sphinx and linkcheck failing for PDFs with anchors has been resolved. This just requires a version of Sphinx with this fix, and requires linkcheck to pass. 
Fixes #414
> Updated dependency to sphinx 7.4.0, and enabled linkcheck testing.

- .github/workflows/main.yml
- doc/source/changelog.rst
- montepy/input_parser/cell_parser.py
- pyproject.toml
- tests/test_cell_problem.py
- tests/test_edge_cases.py
Bug fixes
---------
* Fixed parser bug with parsing cells with implicit intersection, e.g., `(1:-2)(3:-4)`. (#355).
> Release 0.3.1

- doc/source/changelog.rst
- montepy/input_parser/syntax_node.py
- tests/inputs/test.imcnp
- tests/test_syntax_parsing.py
This is a bug fix for the #458. Basically a trailing dollar sign comment would be moved around and on export be put on its own line.
This is because of the way trailing comments are handled. They are moved from the end of the last input to the beginning of the next input as they usually describe the next one. This was being done indiscriminately. This fix only starts moving everything after the first `c` style trailing comment.
This way dollar sign comments stay where they are. 
Fixes #458
> Solved error with trailing dollar-sign comments moving on export

- doc/source/changelog.rst
- montepy/input_parser/syntax_node.py
- tests/inputs/test.imcnp
- tests/test_syntax_parsing.py
Bug fixes
---------
* Fixed bug with trailing dollar sign comments that moved them to a new line. (#458).
> Release 0.3.2

- doc/source/changelog.rst
- montepy/numbered_object_collection.py
- tests/test_numbered_collection.py
Fix bug when with copying numbered objects from one `MCNP_Problem` to another when the new number in the new problem is already in use in the old problem.
Fixes #466
> Test the addition of a numbered object from another problem

- doc/source/changelog.rst
- montepy/input_parser/syntax_node.py
- tests/test_edge_cases.py
This bug was caused by bad type enforcement in `PaddingNode` when it could be passed a `CommentNode` or `str`. Handled this checking for `CommentNode` while appending.
Fixes #461
> Fixed edge case of bad typing in parser

- doc/source/changelog.rst
- montepy/data_inputs/isotope.py
- montepy/data_inputs/material.py
- montepy/input_parser/material_parser.py
- tests/test_material.py
this fixes a bug where material composition data is not updated when written to file. 
This is because the syntax tree was not being properly updated. 
Fixes #470.
> Fix material to update compositions on export

- doc/source/changelog.rst
- montepy/data_inputs/isotope.py
- tests/test_material.py
* New, simpler `Isotope.__repr__`
* Add method `Isotope.nuclide_str()`
* Update _test_material.py_ accordingly
Fixes #473
> Simplify isotope printing with __repr__

- README.md
- doc/source/conf.py
- doc/source/robots.txt
- pyproject.toml
This adds support for robits to our documentation website via `robots.txt` and by creating a `sitemap.xml`, because
Fixes #478.
> Add robits

- doc/source/changelog.rst
- montepy/data_inputs/isotope.py
- tests/test_material.py
This fixed a bug where the metastable state for isotopes (really isomers, but not going to change the class names) was not printed in the string representations. This fixed it using `mN` notation. For example: `U-235m1`.
This also handles the edge case where the ZAID for Am-242m1 (and also Am-242) is intentionally wrong. 
I hate legacy software. 
Fixes #486
> Fixed how metastable isomers are printed. 

- doc/source/changelog.rst
- doc/source/developing.rst
- doc/source/starting.rst
- montepy/__init__.py
- montepy/input_parser/input_file.py
- montepy/mcnp_problem.py
- tests/test_edge_cases.py
- tests/test_integration.py
- tests/test_mcnp_problem.py
* Implement `MCNP_Problem._write_to_stream()` 
* Implement `MCNP_Problem.write_problem()`, which handles both file paths and IO streams.
* Mark `MCNP_Problem.write_to_file()` with a deprecation warning.
* Update the integration and edge case tests accordingly.
* Include `montepy.errors` in top-level namespace
* Convert _test_integration.py_ from unittest to pytest, fixing some minor errors along the way.
* Update documentation accordingly.
Fixes #492
> Write to stream

- doc/source/changelog.rst
- doc/source/developing.rst
- montepy/materials.py
- montepy/mcnp_problem.py
- montepy/numbered_object_collection.py
- tests/test_numbered_collection.py
This makes adding materials a lot more convenient. This is done by making a new subclass of `NumberedObjectCollection`: `NumberedDataObjectCollection`. When an item is added to this (anyway, because under the hood append is always used) it is also added to `problem.data_inputs`. When they are deleted vice versa is true as well. 
Items appended try to reflect user preference by being 1 after the last instance of this type in `data_inputs`. So a new material will be added after the previous final material. 
This isn't perfect but users can always sort `data_inputs` how they please. 
Fixes #465. fixes #93.
> Made method to auto insert new materials to data_inputs.

- doc/source/changelog.rst
- montepy/geometry_operators.py
- montepy/input_parser/cell_parser.py
- montepy/numbered_object_collection.py
- montepy/surfaces/half_space.py
- montepy/utilities.py
- tests/inputs/test_paren_groups.imcnp
- tests/test_edge_cases.py
- tests/test_geometry.py
This fixes a bug where parentheses disappear from the geometry definition of a cell. This was because `surfaces.HalfSpace` essentially had no way to store that information, and when it was time to export the geometry would override the old parentheses. 
This was solved in a few ways.
1. Introduce `Operation.GROUP` to replace `Operation._SHIFT` in this context. This was because this will be more visible to users and `GROUP` is clearer. Also `_SHIFT` is used for certain leaf nodes in complex geometry, and lead to confusion.
2. Adding an unbalanced tree level to `HalfSpace` to represent `GROUP`
3. Updating `HalfSapce` to ensure that `GROUP` is properly handled on export.
4. Made a method to detect when a group needs to be added for scratch geometries. This is done whenever a union node is …
> Bug fix for parentheses getting dropped from cell definitions. 

- .github/scripts/check_sitemap.py
- .github/workflows/main.yml
- README.md
- doc/source/changelog.rst
- doc/source/conf.py
- doc/source/developing.rst
- doc/source/starting.rst
- montepy/__init__.py
- montepy/cell.py
- montepy/data_inputs/cell_modifier.py
- montepy/data_inputs/isotope.py
- montepy/geometry_operators.py
- montepy/input_parser/cell_parser.py
- montepy/input_parser/input_file.py
- montepy/input_parser/syntax_node.py
- montepy/materials.py
- montepy/mcnp_object.py
- montepy/mcnp_problem.py
- montepy/numbered_object_collection.py
- montepy/surfaces/half_space.py
- montepy/utilities.py
- tests/inputs/test_paren_groups.imcnp
- tests/inputs/test_universe_data.imcnp
- tests/test_edge_cases.py
- tests/test_geometry.py
- tests/test_integration.py
- tests/test_material.py
- tests/test_mcnp_problem.py
- tests/test_numbered_collection.py
- tests/test_syntax_parsing.py
Features Added
----
* Write problems to either file paths or streams (file handles) with MCNP_Problem.write_problem() (#492).
* When adding a material to problem.materials it will also be added to problem.data_inputs, ensuring it is printed to the file (#488).
Bug Fixes
----
* Fixed bug that didn't show metastable states for pretty printing and isotope. Also handled the case that Am-241 metstable states break convention (#486).
* Fixed bug where cell modifiers could be made irrelevant by being added after a comment (#483).
* Fixed bug where parentheses in cell geometry are not properly exported (#491).
> Release 0.4.0

- .github/workflows/main.yml
- benchmark/benchmark_big_model.py
- doc/source/changelog.rst
- montepy/data_inputs/data_input.py
- montepy/data_inputs/material.py
- montepy/data_inputs/thermal_scattering.py
- montepy/mcnp_problem.py
- prof/dump_results.py
- prof/profile_big_model.py
- tests/test_material.py
This is a fix of a really inefficient implementation of how `Material` and `ThermalScattering` are linked together during problem setup. The issue is that in `MCNP_Problem`:
``` python
for data_input in self.data_inputs:
data_input.update_pointers(self.data_inputs)
```
This in itself isn't an issue; this is just an O(N) operator, and it's necessary.
But inside of both `Material` and `ThermalScattering` there was:
``` python
def update_pointers(self, data_innputs):
for data_input in data_inputs:
...
```
So this effectively became:
``` python
for data_input_1 in data_inputs:
for data_input_2 in data_inputs:
...
```
This is an O(N<sup>2</sup>) operation. Yikes!
To fix this, I changed:
1. Removed all code from `Material.update_values`
2. Move all linking to `ThermalScattering.update_value`
3. …
> Optimize Material Update Pointers

- doc/source/changelog.rst
- montepy/numbered_object_collection.py
- tests/test_numbered_collection.py
This fixes a bug where `append_renumber` can double add a material to `data_inputs`.
`append_renumber` does:
1. tries to append
2. if failure occurs
3. change the number
4. append again.
`NumberedDataObjectCollection` append was doing:
1. `data_inputs.insert`
2. `super().append`
This fail and retry method led to `data_inputs.insert` being called twice. So making sure `super().append` occurs first fixes this. 
Fixes #516
> Fixed bug double adding materials.

- pyproject.toml
Recently I noticed that some of our links on PyPi are verified, and some are not. This lead to this rabbit hole: https://docs.pypi.org/project_metadata/#verified-details.
Changes:
1. Added a changelog link because that's supported.
2. Corrected capitalization for repo. This was likely blocking the verification.
3. Updated docs page to montepy.org. Note: this will lead to it not being verified.  So not sure if this one should stick.
> Add pyproject link to changelog 

- doc/source/changelog.rst
Quick change to how the changelog is organized to avoid having dozens of top level entries. Added organization at the minor release level. This looks like:
This will be helpful one day if we need to split the changelog into multiple files.
> Added hierarchy to MontePy changelog.

- README.md
- doc/source/bugs.rst
- doc/source/starting.rst
- doc/source/users.rst
- montepy/data_inputs/material.py
Wrote up what materials can't be parsed in the README. Also added a new section in the user guide for issues like this.
Fixes #542.
> Documented what materials can't be parsed

- tests/test_version.py
This fixes test_version to make no assumptions about the users setup. It does this by running `setuptools_scm` first if the `_version.py` file is not present.
Fixes #572
> Fixed test_version to ensure it always has _version.py

- .git_archival.txt
- .gitattributes
- .github/workflows/main.yml
Make it so that `git archive` includes the information necessary for `setuptools_scm` to get a version number. This is based on [this guide](https://setuptools-scm.readthedocs.io/en/stable/usage/#git-archives). Also added a test to make sure this works. 
Fixes #576
> make version info more reliable for git archive

- .git_archival.txt
- .gitattributes
- .github/workflows/main.yml
- doc/source/changelog.rst
- montepy/data_inputs/cell_modifier.py
- montepy/data_inputs/data_input.py
- montepy/data_inputs/importance.py
- montepy/input_parser/parser_base.py
- montepy/input_parser/syntax_node.py
- montepy/input_parser/tally_parser.py
- montepy/mcnp_object.py
- montepy/mcnp_problem.py
- tests/inputs/test.imcnp
- tests/inputs/test_importance.imcnp
- tests/test_integration.py
- tests/test_syntax_parsing.py
- tests/test_version.py
* Fixed AttributeError that occured when a data block IMP was preceded by a comment (#580).
* Fixed bug where tally inputs in a file prevented the file from being pickled or copied (#463).
> Release 0.5.1

- doc/source/changelog.rst
- montepy/errors.py
- montepy/input_parser/input_file.py
- montepy/mcnp_object.py
- montepy/mcnp_problem.py
- montepy/universe.py
This wraps almost errors from `MCNP_Object` with information of where in a file this error came from. This works by:
1. Creating `montepy.errors.add_line_number_to_exception`. This takes an error and a `MCNP_Object` instance. If possible it takes the `_input` information and appends that information to the error message (see below). 
2. Create a `metaclass` (`_ExceptionContextAdder`) for `MCNP_Object` this modifies all attributes. If it's `_private` or `__dunder__` it does nothing. Otherwise for `callable` and `property` it gets wrapped using `_wrap_attr_call`. This just wraps the function call in a `try except`
3. Modularized the pretty-printing function from `ParsingError` for use here to print the input, see below. 
Here is an example stack trace. 
``` python …
```
> Adding more input context to all error messages. 

- CONTRIBUTING.md
- README.md
This is a revision of the README with feedback from @jpmorgan98 as part of the review of MontePy for [pyOpenSCi](https://github.com/pyOpenSci/software-submission/issues/205). 
This included:
* Updating example code to be runnable by `doctest`.
* Added required badges to be PyOpenSci compliant
* Added citation information (will need to update once JOSS article is complete). 
* Added comparisons to competition.
* Updated contributing guide for accuracy.
Currently the too much example code is broken to implement CI testing here, but that is currently in the works in #575. 
Fixes #331
> 331 update readme

- .github/pull_request_template.md
here’s an improved version of your .md checklist file with added sections for documentation standards, details on expected documentation, and coverage reports.
Fixes #591
> Updated Pull Request Checklist

- .github/workflows/main.yml
Yet another follow on to #600. It sounds like we may not get permission for RTD to add a status check to actions for a PR build due to Oauth apps for orgs being all or nothing permissions. This will edit the PR description and link the test build.
FYI: `d` is the hotkey doc diffs which will show what changed from stable for a PR. 
----
📚 Documentation preview 📚: https://montepy--624.org.readthedocs.build/en/624/
> Added RTD action.

- .github/pull_request_template.md
Remove trailing `"""` from _pull_request_template.md_.
**Fixes #621**
---
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--625.org.readthedocs.build/en/625/
> Remove '"""' from PR template

- .github/workflows/main.yml
- .github/workflows/rtd_link.yml
This restricts the RTD action to only there is a potential need for a link to be added to a PR description. This also limits the test workflow to dev PRs. This avoids double runs of the workflow on deploy PRs. 
Follow on to #624 
----
📚 Documentation preview 📚: https://montepy--627.org.readthedocs.build/en/627/
> Rtd action update

- LICENSE
- NOTICE.txt
- doc/source/changelog.rst
- pyproject.toml
Just a few fast fixes. 
* Updates changelog link in meta data
* Fixes superscript in changelog.
Fixes #599
----
📚 Documentation preview 📚: https://montepy--628.org.readthedocs.build/en/628/
> Quick doc updates

- doc/source/changelog.rst
- montepy/__init__.py
- montepy/cells.py
- montepy/data_inputs/importance.py
- montepy/errors.py
- montepy/mcnp_problem.py
- tests/inputs/test_not_imp.imcnp
- tests/test_importance.py
ParticleTypeNotInProblem and ParticleTypeNotInCell are fatal errors. These exceptions arise when the importances of the cells do not agree with those of the run mode. The MCNP6.3 manual does not indicate that these mismatches necessarily result in an unrunnable MCNP model. Therefore, these exceptions have been changed from errors to warnings.
This PR also converts the entirety of _test\_importance.py_ from unittest to pytest.
Fixes #381 
---
---
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--656.org.readthedocs.build/en/656/
> Make Particle Type errors into a warning and a NotImplementedError

- .github/pull_request_template.md
- doc/source/changelog.rst
- montepy/__init__.py
- montepy/constants.py
- montepy/input_parser/input_syntax_reader.py
- montepy/mcnp_object.py
- pyproject.toml
- tests/inputs/test.imcnp
- tests/inputs/test_universe.imcnp
This is probably the most requested feature (whether they say so or not). `LineOverrunWarnings` and `LineExpansionWarnings` are no longer created for comments.
This does the following:
1. Filters out comments from raising warnings, and un-truncate them. 
2. If a line is wrapped on export check if it has a comment.
3. If it's a `c` comment do nothing; do not wrap.
4. If it has a `$` comment wrap the uncommented part, and then add the comment to the end. 
Fixes #188
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--658.org.readthedocs.build/en/658/
> Do not warn about comments that go over the line length

- .github/pull_request_template.md
- montepy/__init__.py
- pyproject.toml
Pin black 25.1 and update the PR template accordingly.
I just cherry-picked commits from the alpha test dev branch
----
📚 Documentation preview 📚: https://montepy--660.org.readthedocs.build/en/660/
> Pin black version '25 

- doc/source/conf.py
This updates a shpinx setting to update the canonical URL to be valid. Canonical URLs is how Search engines decide which page to show when multiple versions exist. Right now this looks like:
``` html
<html lang="en" data-content_root="./" >
<head>
...
<link rel="canonical" href="https://www.montepy.org/starting.html" />
...
```
The update building on RTD now looks like:
``` html 
<html lang="en" data-content_root="./" >
<head>
...
<link rel="canonical" href="https://www.montepy.org/en/stable/starting.html" />
...
```
Related to: https://github.com/openmc-dev/openmc/pull/3324
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: …
> Updated canonical URL for RTD multi-version.

- doc/source/changelog.rst
- doc/source/starting.rst
- montepy/__init__.py
- montepy/data_inputs/material.py
- montepy/materials.py
- tests/test_material.py
- tests/test_numbered_collection.py
This is a feature implementation for `contains`, `get_containing`, and `find`. The topline is that there is a new `strict` argument that switches from implicit to explicit matching. So with `strict=True` `"H"` only matches `1000` and not `1001.80c` nor `1000.80c`. The other main thing was adding some feedback from @gonuke.
This feedback splint `contains` (and `get_containing`) to be: `contains_all` and `contains_any`. This should be clearer to users, and be more useful. The main use case of `contains_any` might be:
``` python
fissile = list(problem.material.get_containing_any("U-235", "U-233", "Pu-239",...)
```
Fixes #642
---
---
</details>
---
<details> …
> Allow strictly finding material components

- doc/source/changelog.rst
- montepy/cell.py
- montepy/cells.py
- montepy/data_inputs/element.py
- montepy/data_inputs/material.py
- montepy/data_inputs/nuclide.py
- montepy/input_parser/syntax_node.py
- montepy/materials.py
- montepy/numbered_mcnp_object.py
- montepy/numbered_object_collection.py
- montepy/surfaces/cylinder_par_axis.py
- montepy/surfaces/half_space.py
- montepy/surfaces/surface.py
- montepy/universe.py
- tests/test_numbers.py
Previously, floating point numbers were enforced as the `float` type and integer numbers were enforced as the `int` type during `isinstance(...)` checking. Now, floating point numbers can be any `Real` type, such as `int`, `uint8`, and `float64`. Similarly, integer numbers can be any `Integral` type, such as `uint8` and `int64`. This leverages the builtin `numbers` module.
Fixes #679.
---
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--680.org.readthedocs.build/en/680/
> Allow any Real type for floating point numbers and any Integral type for integer numbers during type enforcement

- doc/source/changelog.rst
- doc/source/starting.rst
- montepy/_cell_data_control.py
- montepy/cell.py
- montepy/data_inputs/lattice_input.py
- montepy/mcnp_problem.py
- tests/inputs/test_interp_edge.imcnp
- tests/test_cell_problem.py
- tests/test_integration.py
- tests/test_universe_integration.py
This fixes a few bugs with `LAT`, `FILL`, and `U`. The first is that I was getting `LAT=None`. This was fixed by ensuring that everyone was pointing to the same node in the syntax tree.
The other issue is that `problem.print_in_data_block` defaults to `True` which causes confusion for users (me). This default behavior was changed to default to the Cell block. 
Fixes #699
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--701.org.readthedocs.build/en/701/
> Fixed bug where lat, fill, universe not always exporting. 

- doc/source/changelog.rst
- montepy/input_parser/syntax_node.py
- montepy/mcnp_object.py
- montepy/surfaces/surface.py
- tests/test_surfaces.py
This is a quick fix for the case where `is_reflecting=False` did nothing on output. This is because the syntax tree was only updated iff `is_reflecting ^ is_white_boundary` is True. This was a quick fix by giving a final `else`. 
You know in rust had I done something like:
``` rust
match (self.is_reflecting, self.is_white_boundary) {
(True, False) => ...,
(False, True) => ...,
}
```
The compiler would have complained. (Ignore the fact it would have been happy with:
``` rust
if self.is_reflecting {
else if self.is_white_boundary {
}
```
)
* this causes an issue with a continue line if you have four leading spaces: `    *1...` becomes `     1...`. This is because even with `never_pad` the minimum value length of the node is passed to the string formatter. This was solved by:
1. Avoiding …
> Fixed surfaces cant be unset from is reflecting

- doc/source/changelog.rst
- doc/source/starting.rst
- montepy/__init__.py
- montepy/_cell_data_control.py
- montepy/cell.py
- montepy/data_inputs/lattice_input.py
- montepy/data_inputs/universe_input.py
- montepy/input_parser/surface_parser.py
- montepy/input_parser/syntax_node.py
- montepy/mcnp_object.py
- montepy/mcnp_problem.py
- montepy/numbered_mcnp_object.py
- montepy/surfaces/surface.py
- tests/inputs/test_interp_edge.imcnp
- tests/test_cell_problem.py
- tests/test_data_inputs.py
- tests/test_integration.py
- tests/test_surfaces.py
- tests/test_universe_integration.py
* Fixed bug where `surf.is_reflecting` would put an extra space in the output e.g., `* 1 PZ...` (#697).
* Fixed bug where setting a lattice would print as `LAT=None`. Also switched `CellModifier` to print in the cell block by default (#699). 
* Fixed bug that wouldn't allow cloning most surfaces (#704).
* Fixed bug that crashed when some cells were not assigned to any universes (#705).
* Fixed bug where setting `surf.is_reflecting` to `False` did not always get exported properly (#709).
----
📚 Documentation preview 📚: https://montepy--713.org.readthedocs.build/en/713/
> Deploy 1.0.0a4

- doc/source/changelog.rst
- montepy/data_inputs/fill.py
- tests/test_universe.py
This fixes a "bug" where setting `Fill.universes` was not properly exported. There was previously... an effort to implement this, which was not successful. This changed:
1. Making sure `min_index` and `max_index` is always accessible without crashing
2. Setting `min_index` and `max_index` whenever `universes` is set.
3. setting `mulitple_universes=True` whenever `universes` is set. 
4. `_update_cell_values` works properly. 
Fixes #714
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--717.org.readthedocs.build/en/717/
> Allow setting multi-universe fills

- doc/source/changelog.rst
- montepy/data_inputs/data_input.py
- montepy/mcnp_object.py
- tests/test_edge_cases.py
This fixes a bug that was found when a line has to be wrapped (and so a `LineExpansionWarning` is raised). The issue is that the warning meta data was assumed to be a string, but was actually a `list` of all strings in the new wrapped form. This switched them to being strings by just summarizing the change in the number of lines in that expansion. I believe this bug was introduced with #658.
Fixes #721
(Good thing we didn't ship yesterday). 
``` python
In [1]: import montepy
...: import numpy as np
...: problem = montepy.read_input("tests/inputs/test_universe.imcnp")
...: fill = problem.cells[1].fill
...: universes = [montepy.Universe(n) for n in range(300)]
...: fill.universes = np.array([[universes]])
...: problem.write_problem("test.imcnp", overwrite=True) …
```
> Tested new line line expansion bug, #721.

- doc/source/changelog.rst
- montepy/data_inputs/fill.py
- tests/test_universe.py
- tests/test_universe_integration.py
This is a fix for a misinterpretation of how iteration works essentially in `fill`. As discussed in section 5.5.5.3.1 of the 6.3.0 manual:
> Cell-card Form: FILL i1:i2 j1:j2 k1:k2 n1,1,1 n2,1,1 . . . ni1,j1,k1. . . ni2,j2,k2
This implies that you iterate over x, then y, then z: 
This is confirmed by the vignette (section 5.5.5.3.2):
```
FILL=0:2 1:2 0:1 4 4 2 $ i=0,1,2 for j=1 & k=0
2 0 4 0 $ i=0,1,2 for j=2 & k=0
3 0 3 3 $ i=0,1,2 for j=1 & k=1
4 4 4 0 $ i=0,1,2 for j=2 & k=1
```
Mentally this is what I was trying to accomplish, but I foolishly tried to do:
``` python
for i in x_range:
for j in y_range:
for k in z_range:
```
When it should have been:
``` python
for k in z_range:
for j in y_range:
for i in x_range:
```
The latter fixed this. For exporting I switched to `np.flatten` to …
> Handled issue with fill matrices iterating in the wrong order. 

- doc/source/changelog.rst
- montepy/__init__.py
- montepy/cell.py
- montepy/data_inputs/lattice.py
- montepy/data_inputs/lattice_input.py
- tests/test_cell_problem.py
- tests/test_integration.py
- tests/test_syntax_parsing.py
- tests/test_universe.py
- tests/test_universe_integration.py
Fixes #728.
Replaces the `Cell.lattice` property with `Cell.lattice_type`; `lattice.Lattice` with `lattice.LatticeType`; and `HEXAHEDRA` with `HEXAHEDRAL`.
---
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--730.org.readthedocs.build/en/730/
> Rename Cell.lattice -> Cell.lattice_type and deprecate Cell.lattice

- doc/source/changelog.rst
- montepy/__init__.py
- montepy/data_inputs/cell_modifier.py
- montepy/mcnp_object.py
- tests/test_cell_problem.py
- tests/test_importance.py
- tests/test_universe_integration.py
This provides a simple function `mcnp_str` which returns a string as the input would show up in the file. It also adds `montepy.MCNP_VERSION` to make it more obvious what the default version is. This works by just using the default version to run `"\n".join(self.format_for_mcnp_input(...))`. For `CellModifiers` this ensures that something always prints irrespective of `MCNP_Problem.print_in_data_block`, to avoid user confusion. 
Fixes #700 
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--731.org.readthedocs.build/en/731/
> Made lazy mcnp format string

- doc/source/dev_standards.rst
- doc/source/index.rst
This updates documentation:
1. Gives deprecation guidelines.
2. Talks a bit more about versioning.
3. Fixed SEO issue with multiple `<h1>` tags on the home page. 
Fixes #729
Ensure that:
----
📚 Documentation preview 📚: https://montepy--746.org.readthedocs.build/en/746/
> Added deprecation guidelines to developers guide

- .github/pull_request_template.md
- doc/source/changelog.rst
- montepy/input_parser/syntax_node.py
- tests/test_syntax_parsing.py
This fixes the bug with MontePy rounding out changes. This bug came from MontePy trying to match the user's original intent.
This was solved by adding a `rel_eps` and `abs_eps` to the formatter which defaults to `1e-6` and `1e-9` respectively. Making this user settable is a later task: #103. The general approach used is:
1. round to the number of digits from `precision`
2. Compare to the user-set value using `math.isclose` using `rel_eps` and `abs_eps`.
3. If they are not close add another digit of precision and repeat.
I tried to think of away that was not iterative using `log` and `exp` but got stuck. It's really easy to tell the most significant digit, but rather hard to find the least significant digit from my quick research. 
Fixes #756 
---
---
<details open> …
> Fixed bug with bad rounding for floating point value nodes on export

- AUTHORS
- doc/source/_test_for_missing_docs.py
- doc/source/changelog.rst
- montepy/errors.py
- montepy/surfaces/general_plane.py
- montepy/surfaces/surface.py
- pyproject.toml
- tests/test_surfaces.py
Allows for a general plane to have more than 9 constants. Throw a warning if there is strictly more than 9 constants.
Fixes #761
---
---
</details>
---
<details open>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--763.org.readthedocs.build/en/763/
> General plane warning if more than 9 constants.

- .github/pull_request_template.md
- doc/source/changelog.rst
- montepy/cell.py
- montepy/errors.py
- montepy/input_parser/input_syntax_reader.py
- montepy/mcnp_object.py
- tests/inputs/test_broken_mat_link.imcnp
This fixes a bug where MontePy thinks that `5 0 #1` is a Vertical mode input. This is because the complement happens in the first five characters. The fix for this was rather simple, however the error messages are rather vague and useless so users are randomly trying to find vertical mode inputs in their model. This PR:
1. Changes `UnsupportedFeatureError` to be a subclass of `ParsingError`. This is a bit jank because in some contexts it isn't really. But I think for now this is good enough.
2. Provide enough information at exception time to Invoke the `ParsingError` pretty error messages.
3. Detect `#` that is part of different horizontal input by requiring the `#` be the first syntactic element on the line.
Fixes #753
``` python
lineno = 1
token = sly.lex.Token()
token.value = "#"
index …
```
> Fixed detection of vertical mode in cell defintions

- doc/source/changelog.rst
- doc/source/developing.rst
- montepy/data_inputs/data_input.py
- montepy/data_inputs/data_parser.py
- montepy/mcnp_object.py
- tests/test_source.py
- tests/test_source_def.py
- tests/test_tally.py
This was meant to fix the parsing error with `SDEF X=d1`. However, I realized actually supporting and parsing all of `SDEF` syntax is really complicated because you do things like: `SDEF PAR=FCEL=D3`. So I decided to punt full support to #22, and instead put `SDEF` in parsing jail.
However, I realized we never actually implemented parsing jail. So I went back and implemented the parsing jail and added `SDEF` and `DE` to it.
This should really add a lot of ICSBEP input files that we can parse now.
Fixes #755, Fixes #364
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--767.org.readthedocs.build/en/767/
> Fixed parser bug with SDEF with X and Y

- montepy/errors.py
- tests/test_integration.py
This fixes an issue with some tests failing on windows. The errors ultimately came down to file paths being hard coded in strings, and not being platform agnostic. This moves all of that to using `Path()` (for the most part). 
Fixes #745
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--771.org.readthedocs.build/en/771/
> Fixed broken test cases with Windows

- tests/inputs/test_importance.imcnp
This resolves #584, a parsing error with `FQ` inputs. This seems to have been resolved in a previous bug fix, so I am just adding `FQ` to the test suite to act as a regression test. 
I think we can override the changelog test for this, as I  don't think this merits a changelog entry. 
Fixes #584.
---
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--772.org.readthedocs.build/en/772/
> Added FQ input to test suite. 

- README.md
- doc/source/index.rst
- doc/source/robots.txt
This adds some keywords that I learned a user was searching for and barely was able to find MontePy with this search. This tries to add some keywords by using some "use cases" to top level documentation. This will hopefully add useful keywords that SEO will like, without engaging in keyword packing that is penalized, by being natural and actually helpful. Yes this violates my views on the words "card" and "decks". However, I have learned: this is what some users search, and if we want to be helpful, we need to meet the users halfway.
Fixes #754 
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: …
> Added some top level use case info to help with keywords for SEO.

- doc/source/changelog.rst
- montepy/input_parser/input_syntax_reader.py
- tests/inputs/test.imcnp
This fixes a bug where a file that was line-wrapped by MontePy would trigger a `LineOverrunWarning` when read by MontePy. The line-wrapping was manually confirmed to be producing lines that were valid MCNP lengths. This bug was caused by two issues:
1. `\n` was being considered part of the line. This was fixed with `rstrip`
2. `>=` was being used instead of `>`. This was not allowing lines that were exactly at the limit.
This also made the Warning message more helpful. The one question  I struggled with is: should the information past the line length limit be truncated or not? Current behavior is that it is. 
Fixes #517
---
---
</details>
---
<details> …
> Fix bug with over-agressive LineOverRunWarning
