montepy/data_inputs/material.py, tests/test_integration.py
Please include a summary of the change and which issue is fixed if applicable. Please also include relevant motivation and context.
Fixes #395
=> Fix bug with how thermal scattering law data is not written to file

doc/source/changelog.rst
Minor updates due to migration
=> Got changelog up to date and working.

doc/source/changelog.rst, doc/source/index.rst
Added link to PyPI project to the links section of the sphinx index. 
Fixes #410.
=> Added link to PyPI project.

CNAME
Just quick update to tell pages what the CNAME is and reflect the actual pages configuration.
=> Update CNAME to use www subdomain

.github/workflows/deploy.yml, README.md, doc/source/changelog.rst, doc/source/faq.rst, doc/source/scope.rst
Quick section in FAQ with a link to the longer answer. 
Fixes #400
=> Added discussion of why MCNP output files aren't supported to FAQ.

doc/source/index.rst
Link to the new MCNP forum on Discourse in the "See Also" section.
Closes #434
=> Link to MCNP discourse

CODE_OF_CONDUCT.md
Please include a summary of the change and which issue is fixed if applicable. Please also include relevant motivation and context.
Fixes # (issue)
=> Create default CODE_OF_CONDUCT.md

.github/scripts/check_sitemap.py, .github/workflows/main.yml, doc/source/conf.py
This fixes the URL in the sitemap to be the actual URLs. It also implements testing that requires that 80% of the URLs in the sitemap to be accurate (code 200).
Fixes #494
=> Fixed sitemap URLs   

README.md
=> Update README for pending release

doc/source/changelog.rst, doc/source/migrations/migrate0_1.rst, montepy/errors.py, montepy/input_parser/input_file.py, montepy/mcnp_object.py, montepy/particle.py, montepy/universe.py
This is a quick edit to prepare for migration to `1.0.0.a1`. It is just meant to have more information to prepare users for how they will need to migrate. It is not finalized as effective documentation will link to the new docstrings... which can't be linked to yet.
=> Mat docs upate

.github/workflows/main.yml, pyproject.toml
This is our first post release. Mostly doing this to test the process out.
This just changed the sly dependencies to be broader.
=> Release 0.5.3.post1

.github/workflows/deploy.yml, CNAME, README.md
This is the final step in the RTD deployment process, and a follow-up to #600. Part of #615
=> Delete GH pages deploy process.

README.md, doc/source/developing.rst
It's on conda-forge now! https://github.com/conda-forge/montepy-feedstock?tab=readme-ov-file
=> Added conda forge badge.

.github/workflows/main.yml
Short CI/CD update to keep at least one set of build artifacts. 
Fixes #633
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--644.org.readthedocs.build/en/644/
=> Updated CI/CD to keep build artifacts. 

montepy/cell.py, montepy/data_inputs/material.py
Yolo. 
----
📚 Documentation preview 📚: https://montepy--662.org.readthedocs.build/en/662/
=> Added a few MCNP 6.3.1 links.

doc/source/dev_standards.rst
This is just a documentation update to write down our naming conventions (or at least our lofty goals). Link to the docs update: https://montepy--693.org.readthedocs.build/en/693/dev_standards.html#naming-conventions
Fixes #157 
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--693.org.readthedocs.build/en/693/
=> Documented naming conventions.

doc/source/changelog.rst, montepy/data_inputs/universe_input.py, tests/test_universe_integration.py
Please provide a summary of the change, referencing the issue it fixes, if applicable. Include relevant context and motivation.
Fixes #705
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--707.org.readthedocs.build/en/707/
=> 705 bug with no default universe

README.md
Please provide a summary of the change, referencing the issue it fixes, if applicable. Include relevant context and motivation.
Fixes # (issue number)
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--712.org.readthedocs.build/en/712/
=> Added PyOpenSci and Zenodo badges.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Pretty clear and self-explanatory. 
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--725.org.readthedocs.build/en/725/
=> Updated templates to use type, and be more legible.

README.md
Just a quick typo I found in the README. 
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--732.org.readthedocs.build/en/732/
=> Fixed markdown typos and updated priorities.

CITATION.cff, README.md, doc/source/dev_checklist.rst, doc/source/publications.rst
Please provide a summary of the change, referencing the issue it fixes, if applicable. Include relevant context and motivation.
Fixes #739, Fixes #718, Fixes #734
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--740.org.readthedocs.build/en/740/
=> Updated Zenodo archive link.

doc/source/index.rst
Please provide a summary of the change, referencing the issue it fixes, if applicable. Include relevant context and motivation.
Fixes #751 
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--758.org.readthedocs.build/en/758/
=> Added JOSS to home page.

.github/dependabot.yml, .github/workflows/deploy.yml, .github/workflows/main.yml
This PR adopts some best practices security-wise (from a survey on security practices you use).
1. This pins all GH actions not developed by GH to a specific commit to avoid "vender-side attacks"
2. It enables weekly scanning by dependabot for vulnerabilities in dependencies as well creating out fix PRs for this. 
Fixes #770 
---
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--773.org.readthedocs.build/en/773/
=> Manage GH actions security 

.github/workflows/main.yml, README.md, doc/source/changelog.rst, doc/source/dev_standards.rst, pyproject.toml
This changes the dependencies, and adopts SPEC 0. 
Fixes #780
---
---
</details>
---
<details>
</details>
---
Ensure that:
----
📚 Documentation preview 📚: https://montepy--781.org.readthedocs.build/en/781/
=> adopt spec 0

doc/source/changelog.rst, montepy/data_inputs/material.py, montepy/data_inputs/nuclide.py, montepy/numbered_object_collection.py, pyproject.toml
Added descriptive error messages to blank TypeError exceptions highlighted in the issue #801.
**Changes made:**
- Added descriptive message to TypeError in `material.py` line 65 (__setitem__ method)
- Added descriptive message to TypeError in `material.py` line 94 (_validate_key method) 
- Added descriptive message to TypeError in `numbered_object_collection.py` line 362 (remove method)
Fixes #801 
---
---
</details>
---
<details>
</details>
---
Ensure that:
=> Filling exception messages

tests/test_cell_problem.py, tests/test_data_inputs.py, tests/test_edge_cases.py, tests/test_geometry.py, tests/test_input_file.py, tests/test_integration.py, tests/test_interface.py, tests/test_main.py, tests/test_mode.py, tests/test_scripts.py, tests/test_surfaces.py, tests/test_transform.py, tests/test_universe.py, tests/test_utilities.py
There's a lot of test suite maintenance that I have been putting off. I finally decided to ask copilot (with GPT-4.1) to do most of this work, and it got there with moderate babysitting, and a few avoided catastrophes.
Changes:
1. Remove `UnitTest` and complete switch to `pytest`
2. Removal of most test suite classes
3. Removal of all setting and reference to `_mutated`
4. Removed most uses of `str`->`Input`-> constructor patterns
5. Removed most references to `card`
6. Creates some `@parameterized` tests
| Branch | `Develop` | `full_pytest` |
|--------|-----------|---------------|
| Num tests| 863     | 932
| Coverage |97.9149% | 97.9149% |
|Coverage lines missed | 170 | 170 |
Fixes #464, fixes #390
---
---
</details> …
=> Full test suite re-org
